[functions.evidence-collector-v8]
# Evidence Collector v8 Configuration
# Deep, agentic evidence collection with comprehensive audit trail

# Crawl4AI-inspired deep crawling settings
[crawler]
max_depth = 5
max_pages = 200
parallel_requests = 5
js_rendering = true
follow_external_links = true
timeout_per_page = 30000

# Extraction patterns
extraction_patterns = [
  "tech-stack",
  "team-info",
  "api-endpoints",
  "business-metrics",
  "security-headers",
  "financial-data",
  "customer-testimonials",
  "case-studies",
  "job-postings",
  "investor-info"
]

# Agentic search configuration
[agentic_search]
max_search_depth = 5
searches_per_phase = 10
enable_adaptive_planning = true
enable_gap_analysis = true

# Search types
search_types = [
  "technical",
  "business",
  "financial",
  "competitive",
  "team",
  "investor",
  "customer",
  "market",
  "strategic"
]

# Evidence quality thresholds
[quality]
min_confidence = 0.5
high_quality_threshold = 0.8
evidence_target = 200
high_quality_target = 100

# Audit trail settings
[audit]
enable_full_audit = true
log_decisions = true
log_reasoning = true
track_evidence_lineage = true

# Tool integration
[tools]
enable_all_tools = true
parallel_tool_execution = true
tool_timeout = 60000

# Available tools
enabled_tools = [
  "html-collector",
  "webtech-analyzer",
  "security-scanner",
  "testssl-scanner",
  "performance-analyzer",
  "nuclei-scanner",
  "google-search-collector",
  "playwright-crawler",
  "jina-data-collector",
  "har-capture",
  "deep-research-collector"
]

# Investment thesis configurations
[thesis.accelerate-organic-growth]
priority_evidence = ["growth-metrics", "marketing-tech", "customer-acquisition"]
search_focus = ["growth", "marketing", "expansion"]

[thesis.buy-and-build]
priority_evidence = ["acquisition-history", "integration-capability", "market-position"]
search_focus = ["M&A", "acquisitions", "integration"]

[thesis.digital-transformation]
priority_evidence = ["tech-modernization", "cloud-adoption", "api-strategy"]
search_focus = ["digital", "transformation", "modernization"]

[thesis.generative-ai-adoption]
priority_evidence = ["ai-tools", "ml-infrastructure", "data-pipelines"]
search_focus = ["AI", "machine learning", "LLM", "generative"]